// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyBFo0SEa-hxT3P0NLfJ64ydZJuLc-3oggw",
      authDomain: "chatwithfirebase-19579.firebaseapp.com",
      databaseURL: "https://chatwithfirebase-19579-default-rtdb.firebaseio.com",
      projectId: "chatwithfirebase-19579",
      storageBucket: "chatwithfirebase-19579.appspot.com",
      messagingSenderId: "1014607047105",
      appId: "1:1014607047105:web:8385310a4f02369762e740",
      measurementId: "G-1N9GNHN6VM"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYQFJThZ_NNHuuK--UYq-Tqq9B8J2OL2s',
    appId: '1:51589792579:android:3e84890c8574c8955ba5f6',
    messagingSenderId: '51589792579',
    projectId: 'quanlyphuongtien-22dd4',
    databaseURL: 'https://quanlyphuongtien-22dd4-default-rtdb.firebaseio.com',
    storageBucket: 'quanlyphuongtien-22dd4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaUbZPy9fLegXrGdIktA-XvoMs_OhSOe0',
    appId: '1:51589792579:ios:0c0ef11e125b1aee5ba5f6',
    messagingSenderId: '51589792579',
    projectId: 'quanlyphuongtien-22dd4',
    databaseURL: 'https://quanlyphuongtien-22dd4-default-rtdb.firebaseio.com',
    storageBucket: 'quanlyphuongtien-22dd4.appspot.com',
    iosBundleId: 'com.example.quanlyhocsinh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaUbZPy9fLegXrGdIktA-XvoMs_OhSOe0',
    appId: '1:51589792579:ios:0c0ef11e125b1aee5ba5f6',
    messagingSenderId: '51589792579',
    projectId: 'quanlyphuongtien-22dd4',
    databaseURL: 'https://quanlyphuongtien-22dd4-default-rtdb.firebaseio.com',
    storageBucket: 'quanlyphuongtien-22dd4.appspot.com',
    iosBundleId: 'com.example.quanlyhocsinh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1ao20BuCfBbjROooGzn_qbO8x3XJoFHU',
    appId: '1:51589792579:web:1464acf52115bdba5ba5f6',
    messagingSenderId: '51589792579',
    projectId: 'quanlyphuongtien-22dd4',
    authDomain: 'quanlyphuongtien-22dd4.firebaseapp.com',
    databaseURL: 'https://quanlyphuongtien-22dd4-default-rtdb.firebaseio.com',
    storageBucket: 'quanlyphuongtien-22dd4.appspot.com',
    measurementId: 'G-19Q7JLB6ZX',
  );

}